#!/bin/bash

# Define the directory where files should be created
export APPENDRC_PATH="$BASH_FILES_DIR/repos/appendrc"

# Function to create a new file and open it with the default editor
appendrc() {
    local filename="$1"

    # Ensure a filename was provided
    if [[ -z "$filename" ]]; then
        echo "Usage: appendrc filename"
        echo "Creates an appendrc file that allows bash_files to source it"
        return
    fi
    
    # Ensure the directory exists
    mkdir -p "$APPENDRC_PATH"
    
    # Create the new file
    local filepath="$APPENDRC_PATH/$filename"
    touch "$filepath"

    # add default content to the file
    cat > "$filepath" <<- 'EOF'
	# [ -f "$HOME/.example_package/env" ] && "$HOME/.example_package/env"
	EOF
    
    # Open the file with the default editor
    ${EDITOR:-nano} "$filepath"
}

# Check if the script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # Call the appendrc function with the first argument
    appendrc "$1"
fi
