use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, exit};
use std::time::Instant;

fn home_dir() -> PathBuf {
    PathBuf::from(env::var("HOME").unwrap_or_else(|_| {
        eprintln!("error: HOME environment variable not set");
        exit(1);
    }))
}

fn state_dir() -> PathBuf {
    home_dir().join(".appendrc")
}

fn sourcables_dir() -> PathBuf {
    state_dir().join("sourcables")
}

fn timing_json_path() -> PathBuf {
    state_dir().join("timing.json")
}

fn fast_sh_path() -> PathBuf {
    state_dir().join("fast.sh")
}

fn path_list_path() -> PathBuf {
    state_dir().join("path_list.txt")
}

fn paths_sourcable_path() -> PathBuf {
    sourcables_dir().join("000_paths.sh")
}

fn ensure_dirs() {
    fs::create_dir_all(sourcables_dir()).unwrap_or_else(|e| {
        eprintln!("error: failed to create state dirs: {}", e);
        exit(1);
    });
}

// ── timing.json helpers ──────────────────────────────────────────────────────

fn read_timing() -> HashMap<String, f64> {
    let path = timing_json_path();
    if !path.exists() {
        return HashMap::new();
    }
    let content = fs::read_to_string(&path).unwrap_or_default();
    parse_timing_json(&content)
}

fn parse_timing_json(content: &str) -> HashMap<String, f64> {
    let mut map = HashMap::new();
    let content = content.trim();
    // expect: {"key": value, "key2": value2}
    if content.is_empty() || content == "{}" {
        return map;
    }
    // strip outer braces
    let inner = content
        .trim_start_matches('{')
        .trim_end_matches('}');
    // split on commas that are not inside quotes — simple heuristic:
    // since keys and values have no nested structures, split on ',' after a number
    let mut chars = inner.chars().peekable();
    loop {
        // skip whitespace
        while chars.peek().map(|c| c.is_whitespace()).unwrap_or(false) {
            chars.next();
        }
        if chars.peek().is_none() {
            break;
        }
        // expect '"'
        if chars.peek() != Some(&'"') {
            break;
        }
        chars.next(); // consume '"'
        let mut key = String::new();
        for c in chars.by_ref() {
            if c == '"' {
                break;
            }
            key.push(c);
        }
        // skip whitespace and ':'
        while chars.peek().map(|c| c.is_whitespace() || *c == ':').unwrap_or(false) {
            chars.next();
        }
        // read number
        let mut num = String::new();
        while chars.peek().map(|c| c.is_ascii_digit() || *c == '.' || *c == 'e' || *c == 'E' || *c == '-' || *c == '+').unwrap_or(false) {
            num.push(chars.next().unwrap());
        }
        if let Ok(val) = num.parse::<f64>() {
            map.insert(key, val);
        }
        // skip whitespace and optional comma
        while chars.peek().map(|c| c.is_whitespace() || *c == ',').unwrap_or(false) {
            chars.next();
        }
    }
    map
}

fn write_timing(map: &HashMap<String, f64>) {
    let path = timing_json_path();
    let mut entries: Vec<(&String, &f64)> = map.iter().collect();
    entries.sort_by_key(|(k, _)| k.as_str());
    let mut json = String::from("{");
    for (i, (k, v)) in entries.iter().enumerate() {
        if i > 0 {
            json.push_str(", ");
        }
        json.push('"');
        json.push_str(k);
        json.push_str("\": ");
        json.push_str(&format!("{:.6}", v));
    }
    json.push('}');
    fs::write(&path, json).unwrap_or_else(|e| {
        eprintln!("error: failed to write timing.json: {}", e);
        exit(1);
    });
}

// ── fast.sh helpers ──────────────────────────────────────────────────────────

fn rebuild_fast_sh(timing: &HashMap<String, f64>) {
    let src_dir = sourcables_dir();
    let mut fast_files: Vec<String> = timing
        .iter()
        .filter(|(_, &v)| v < 1.0)
        .map(|(k, _)| k.clone())
        .collect();
    fast_files.sort();

    let mut lines = String::from("# Generated by appendrc time\n");
    for name in &fast_files {
        let file_path = src_dir.join(name);
        lines.push_str(&format!("source {}\n", file_path.display()));
    }
    fs::write(fast_sh_path(), lines).unwrap_or_else(|e| {
        eprintln!("error: failed to write fast.sh: {}", e);
        exit(1);
    });
}

// ── path management helpers ──────────────────────────────────────────────────

fn read_path_list() -> Vec<String> {
    let path = path_list_path();
    if !path.exists() {
        return Vec::new();
    }
    let content = fs::read_to_string(&path).unwrap_or_default();
    content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.to_string())
        .collect()
}

fn write_path_list(paths: &[String]) {
    let content = paths.join("\n") + if paths.is_empty() { "" } else { "\n" };
    fs::write(path_list_path(), content).unwrap_or_else(|e| {
        eprintln!("error: failed to write path_list.txt: {}", e);
        exit(1);
    });
}

fn regenerate_paths_sh(paths: &[String]) {
    let mut content = String::from("# Managed by appendrc path\n");
    content.push_str("_arc_path_add() { [ -d \"$1\" ] && case \":$PATH:\" in *\":$1:\"*) ;; *) export PATH=\"$1:$PATH\" ;; esac; }\n");
    for p in paths {
        content.push_str(&format!("_arc_path_add \"{}\"\n", p));
    }
    content.push_str("unset -f _arc_path_add\n");
    fs::write(paths_sourcable_path(), content).unwrap_or_else(|e| {
        eprintln!("error: failed to write 000_paths.sh: {}", e);
        exit(1);
    });
}

// ── editor ───────────────────────────────────────────────────────────────────

fn open_editor(path: &Path) {
    let editor = env::var("EDITOR").unwrap_or_else(|_| "nano".to_string());
    let status = Command::new(&editor)
        .arg(path)
        .status()
        .unwrap_or_else(|e| {
            eprintln!("error: failed to launch editor '{}': {}", editor, e);
            exit(1);
        });
    if !status.success() {
        eprintln!("error: editor exited with non-zero status");
        exit(1);
    }
}

// ── commands ─────────────────────────────────────────────────────────────────

fn cmd_add(name: &str, content: Option<&str>) {
    ensure_dirs();
    let file_path = sourcables_dir().join(name);
    if let Some(text) = content {
        fs::write(&file_path, text).unwrap_or_else(|e| {
            eprintln!("error: failed to write file: {}", e);
            exit(1);
        });
        println!("created {}", file_path.display());
    } else {
        // create empty file if it doesn't exist, then open editor
        if !file_path.exists() {
            fs::write(&file_path, "").unwrap_or_else(|e| {
                eprintln!("error: failed to create file: {}", e);
                exit(1);
            });
        }
        open_editor(&file_path);
        println!("saved {}", file_path.display());
    }
}

fn cmd_edit(name: &str) {
    ensure_dirs();
    let file_path = sourcables_dir().join(name);
    if !file_path.exists() {
        eprintln!("error: '{}' does not exist", name);
        exit(1);
    }
    open_editor(&file_path);
}

fn cmd_remove(name: &str) {
    ensure_dirs();
    let file_path = sourcables_dir().join(name);
    if !file_path.exists() {
        eprintln!("error: '{}' does not exist", name);
        exit(1);
    }
    fs::remove_file(&file_path).unwrap_or_else(|e| {
        eprintln!("error: failed to remove file: {}", e);
        exit(1);
    });
    // remove from timing.json
    let mut timing = read_timing();
    timing.remove(name);
    write_timing(&timing);
    // rebuild fast.sh
    rebuild_fast_sh(&timing);
    println!("removed {}", name);
}

fn cmd_list() {
    ensure_dirs();
    let timing = read_timing();
    let src_dir = sourcables_dir();
    let mut entries: Vec<String> = fs::read_dir(&src_dir)
        .unwrap_or_else(|e| {
            eprintln!("error: failed to read sourcables dir: {}", e);
            exit(1);
        })
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_file())
        .filter_map(|e| e.file_name().into_string().ok())
        .collect();
    entries.sort();
    if entries.is_empty() {
        println!("no sourcable files found");
        return;
    }
    for name in &entries {
        let tag = match timing.get(name) {
            Some(&t) if t < 1.0 => format!("[fast] ({:.3}s)", t),
            Some(&t) => format!("[slow] ({:.3}s)", t),
            None => "[?]".to_string(),
        };
        println!("{} {}", name, tag);
    }
}

fn cmd_time() {
    ensure_dirs();
    let src_dir = sourcables_dir();
    let mut entries: Vec<String> = fs::read_dir(&src_dir)
        .unwrap_or_else(|e| {
            eprintln!("error: failed to read sourcables dir: {}", e);
            exit(1);
        })
        .filter_map(|e| e.ok())
        .filter(|e| e.path().is_file())
        .filter_map(|e| e.file_name().into_string().ok())
        .collect();
    entries.sort();

    let mut timing: HashMap<String, f64> = HashMap::new();

    for name in &entries {
        let file_path = src_dir.join(name);
        let file_str = file_path.to_string_lossy().to_string();
        let start = Instant::now();
        let result = Command::new("bash")
            .args(["-c", &format!("source '{}'", file_str)])
            .output();
        let elapsed = start.elapsed().as_secs_f64();
        match result {
            Ok(_) => {
                timing.insert(name.clone(), elapsed);
                let tag = if elapsed < 1.0 { "fast" } else { "slow" };
                println!("{}: {:.3}s [{}]", name, elapsed, tag);
            }
            Err(e) => {
                eprintln!("warning: failed to time '{}': {}", name, e);
            }
        }
    }

    write_timing(&timing);
    rebuild_fast_sh(&timing);
    println!("timing.json updated, fast.sh rebuilt");
}

fn cmd_source(fast: bool) {
    ensure_dirs();
    if fast {
        let fast_path = fast_sh_path();
        if !fast_path.exists() {
            eprintln!("error: fast.sh not found, run 'appendrc time' first");
            exit(1);
        }
        let content = fs::read_to_string(&fast_path).unwrap_or_default();
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("source ") {
                println!("{}", trimmed);
            }
        }
    } else {
        let src_dir = sourcables_dir();
        let mut entries: Vec<String> = fs::read_dir(&src_dir)
            .unwrap_or_else(|e| {
                eprintln!("error: failed to read sourcables dir: {}", e);
                exit(1);
            })
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_file())
            .filter_map(|e| e.file_name().into_string().ok())
            .collect();
        entries.sort();
        for name in &entries {
            let file_path = src_dir.join(&name);
            println!("source {}", file_path.display());
        }
    }
}

fn cmd_path_add(path_str: &str) {
    ensure_dirs();
    let mut paths = read_path_list();
    if paths.iter().any(|p| p == path_str) {
        println!("path already managed: {}", path_str);
        return;
    }
    paths.push(path_str.to_string());
    write_path_list(&paths);
    regenerate_paths_sh(&paths);
    println!("added path: {}", path_str);
}

fn cmd_path_remove(path_str: &str) {
    ensure_dirs();
    let mut paths = read_path_list();
    let before = paths.len();
    paths.retain(|p| p != path_str);
    if paths.len() == before {
        eprintln!("error: path not found: {}", path_str);
        exit(1);
    }
    write_path_list(&paths);
    regenerate_paths_sh(&paths);
    println!("removed path: {}", path_str);
}

fn cmd_path_list() {
    let paths = read_path_list();
    if paths.is_empty() {
        println!("no managed paths");
        return;
    }
    for p in &paths {
        println!("{}", p);
    }
}

fn cmd_help() {
    println!("appendrc — manage sourcable shell files in ~/.appendrc/sourcables/");
    println!();
    println!("USAGE:");
    println!("  appendrc <command> [args]");
    println!();
    println!("COMMANDS:");
    println!("  add <name> [content]   Create a sourcable file. Opens $EDITOR if no content given.");
    println!("  edit <name>            Open a sourcable file in $EDITOR.");
    println!("  remove <name>          Delete a sourcable file.");
    println!("  list                   List all sourcable files with timing info.");
    println!("  time                   Benchmark all sourcable files and rebuild fast.sh.");
    println!("  source [--fast]        Print source commands. Use: eval \"$(appendrc source)\"");
    println!("                         --fast  Only include files that sourced in under 1s.");
    println!("  path add <path>        Add a path to managed PATH list.");
    println!("  path remove <path>     Remove a path from managed PATH list.");
    println!("  path list              List managed paths.");
    println!("  help                   Show this help.");
}

// ── main ─────────────────────────────────────────────────────────────────────

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() < 2 {
        cmd_help();
        return;
    }

    match args[1].as_str() {
        "add" => {
            if args.len() < 3 {
                eprintln!("usage: appendrc add <name> [content]");
                exit(1);
            }
            let name = &args[2];
            let content = if args.len() > 3 {
                Some(args[3..].join(" ").as_str().to_string())
            } else {
                None
            };
            cmd_add(name, content.as_deref());
        }
        "edit" => {
            if args.len() < 3 {
                eprintln!("usage: appendrc edit <name>");
                exit(1);
            }
            cmd_edit(&args[2]);
        }
        "remove" | "rm" => {
            if args.len() < 3 {
                eprintln!("usage: appendrc remove <name>");
                exit(1);
            }
            cmd_remove(&args[2]);
        }
        "list" | "ls" => {
            cmd_list();
        }
        "time" => {
            cmd_time();
        }
        "source" => {
            let fast = args.get(2).map(|a| a == "--fast").unwrap_or(false);
            cmd_source(fast);
        }
        "path" => {
            if args.len() < 3 {
                eprintln!("usage: appendrc path <add|remove|list> [path]");
                exit(1);
            }
            match args[2].as_str() {
                "add" => {
                    if args.len() < 4 {
                        eprintln!("usage: appendrc path add <path>");
                        exit(1);
                    }
                    cmd_path_add(&args[3]);
                }
                "remove" | "rm" => {
                    if args.len() < 4 {
                        eprintln!("usage: appendrc path remove <path>");
                        exit(1);
                    }
                    cmd_path_remove(&args[3]);
                }
                "list" | "ls" => {
                    cmd_path_list();
                }
                sub => {
                    eprintln!("error: unknown path subcommand '{}'", sub);
                    eprintln!("usage: appendrc path <add|remove|list> [path]");
                    exit(1);
                }
            }
        }
        "help" | "--help" | "-h" => {
            cmd_help();
        }
        "--version" | "-V" => {
            println!("appendrc {}", env!("CARGO_PKG_VERSION"));
        }
        cmd => {
            eprintln!("error: unknown command '{}'", cmd);
            eprintln!("run 'appendrc help' for usage");
            exit(1);
        }
    }
}
